# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[(b'STARTED', b'STARTED'), (b'FAILED', b'FAILED'), (b'SUCCESS', b'SUCCESS')], default=b'STARTED')),
                ('client_ip', models.TextField(default=b'')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('completed', models.DateTimeField(auto_now=True)),
                ('remote', models.URLField()),
                ('file_name', models.TextField()),
                ('base64encode', models.BooleanField(default=False)),
            ],
        ),
    ]
