# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='git_branches',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='download',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
